services:
  api:
    build:
      context: ./track-backend
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://mongodb:27017/mydatabase

  portal:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
      args:
        VITE_APP_API: http://api:5000
    ports:
      - "8081:80"
    depends_on:
      - api

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data: